### ISSUE TITLE
Possible fix?

### ISSUE THREAD

**Issue by ChefMC** [askblaker/sveltekit-api-benchmark#1]
Hi. Will [this adapter](https://www.jsdelivr.com/package/npm/svelte-adapter-fastify) help to solve SvelteKit performance? 
Can you publish benchmark using that solution? Thanks!

**Comment by askblaker** [comment]
Hey. Thanks for the idea.

The adapter does however look unmaintained, so I don't think I'll go for it. 

Feel free to let me know if you find a maintained adapter in the future. It's an interesting idea.
